//columns
GET http://localhost:3001/columns

###
//cards
#Metodo para llamar columnas con array de tarjetas, por el momento se desusa
#GET http://localhost:3001/6457c92966f406a39e79b878p/cards
#Content-Type: application/json
#
#{
#  "columnId": "6457c92966f406a39e79b878"
#}
###
GET http://localhost:3001/cards

###
POST http://localhost:3001/card/new
Content-Type: application/json

{
  "text": "nuevo esquema",
  "columnId": "6457c92966f406a39e79b878",
  "amountOfLikes": 0,
  "isLike": true
}

###

DELETE http://localhost:3001/card/delete/6457ee4eeccf7fc356b60256

###

PUT http://localhost:3001/card/edit/64582501ef38404329263392
Content-Type: application/json

{
  "text": "EXPERIMENTO",
  "column": "6457f4aac643c4e0fe96d497",
  "amountOfLikes": 99,
  "isLike": true
}