//columns
GET http://localhost:3001/columns

###
//cards
GET http://localhost:3001/cards

###
POST http://localhost:3001/card/new
Content-Type: application/json

{
  "text": "nueva tarjeta num 2",
  "columnId": "645be27a25286b34519fddf1",
  "amountOfLikes": 0,
  "isLike": true
}

###

DELETE http://localhost:3001/card/delete/645be35425286b34519fde01

###

PUT http://localhost:3001/card/edit/645be32a25286b34519fddfd
Content-Type: application/json

{
  "text": "se modifica nueva tarjeta num 2",
  "column": "645be27a25286b34519fddf1",
  "amountOfLikes": 99,
  "isLike": true
}

###
//comments
POST http://localhost:3001/cards/comment
Content-Type: application/json

{
  "text": "un comentario",
  "cardId": "645be58076bc5c3474888d9e"
}